import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class insert_university_converter {

    public static void main(String[] args) {

        // ❗ 1. 여기에 읽어올 CSV 파일의 경로를 입력하세요.
        String inputFilePath = "학교개황(20250507 기준).csv";

        // ❗ 2. 여기에 생성할 SQL 파일의 경로와 이름을 입력하세요.
        String outputFilePath = "insert_university.sql";

        // ❗ 3. CSV 파일의 구분자(delimiter)를 지정하세요. (쉼표: ",", 탭: "\t")
        String DELIMITER = ",";

        // try-with-resources 구문을 사용하여 파일 리더와 라이터를 자동으로 닫습니다.
        try (BufferedReader reader = new BufferedReader(new FileReader(inputFilePath));
             BufferedWriter writer = new BufferedWriter(new FileWriter(outputFilePath))) {

            writer.write("-- Universities Table INSERT Statements Generated by Java --\n");
            writer.newLine(); // 줄바꿈

            String line;
            boolean isFirstLine = true; // 첫 번째 줄(헤더)을 건너뛰기 위한 플래그

            // 파일의 끝에 도달할 때까지 한 줄씩 읽습니다.
            while ((line = reader.readLine()) != null) {
                if (isFirstLine) {
                    isFirstLine = false;
                    continue;
                }

                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] columns = line.split(DELIMITER);

                if (columns.length != 7) {
                    System.err.println("Skipping malformed line: " + line);
                    continue;
                }

                // CSV 데이터 추출
                String universityId = columns[1].trim();
                String universityName = columns[2].trim().replace("'", "''"); // SQL Injection 방지를 위해 작은 따옴표 처리
                String campusType = columns[3].trim();
                String academicSystem = columns[4].trim();
                String region = columns[5].trim();
                String establishmentType = columns[6].trim();

                // SQL INSERT 문 생성
                String insertSql = String.format(
                        "INSERT INTO universities (university_id, university_name, campus_type, academic_system, region, establishment_type, university_level) VALUES (%s, '%s', '%s', '%s', '%s', '%s', NULL);",
                        universityId, universityName, campusType, academicSystem, region, establishmentType
                );

                // 생성된 SQL 문을 파일에 쓰고 줄바꿈
                writer.write(insertSql);
                writer.newLine();
            }

            System.out.println("✅ SQL 파일 생성이 완료되었습니다.");
            System.out.println("   -> 저장된 파일: " + outputFilePath);

        } catch (IOException e) {
            System.err.println("❌ 파일 처리 중 오류가 발생했습니다: " + e.getMessage());
            e.printStackTrace();
        }
    }
}

