import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class insert_departments_converter {

    public static void main(String[] args) {

        // ❗ 1. 여기에 읽어올 학과 CSV 파일의 경로를 입력하세요.
        String inputFilePath = "학교별 교육편제단위 정보_20250221기준.csv";

        // ❗ 2. 여기에 생성할 SQL 파일의 경로와 이름을 입력하세요.
        String outputFilePath = "insert_departments.sql";

        // ❗ 3. CSV 파일의 구분자(delimiter)를 지정하세요. (쉼표: ",", 탭: "\t")
        String DELIMITER = ",";

        // try-with-resources 구문을 사용하여 파일 리더와 라이터를 자동으로 닫습니다.
        try (BufferedReader reader = new BufferedReader(new FileReader(inputFilePath));
             BufferedWriter writer = new BufferedWriter(new FileWriter(outputFilePath))) {

            writer.write("-- Departments Table INSERT Statements Generated by Java --\n");
            writer.newLine();

            String line;
            boolean isFirstLine = true; // 첫 번째 줄(헤더)을 건너뛰기 위한 플래그
            int successCount = 0;

            // 파일의 끝에 도달할 때까지 한 줄씩 읽습니다.
            while ((line = reader.readLine()) != null) {
                if (isFirstLine) {
                    isFirstLine = false;
                    continue;
                }

                if (line.trim().isEmpty()) {
                    continue;
                }

                String[] columns = line.split(DELIMITER);

                // CSV 열이 최소 3개 이상인지 확인합니다. (학교코드, 학과코드, 학과명)
                if (columns.length < 3) {
                    System.err.println("Skipping malformed line (not enough columns): " + line);
                    continue;
                }

                // CSV의 첫 3개 열에서 데이터를 추출합니다.
                String universityId = columns[0].trim();
                String departmentId = columns[1].trim();
                // 학과명에 포함된 작은따옴표(')가 SQL 오류를 일으키지 않도록 처리합니다.
                String departmentName = columns[2].trim().replace("'", "''");

                // SQL INSERT 문을 형식에 맞게 생성합니다.
                String insertSql = String.format(
                        "INSERT INTO departments (university_id, department_id, department_name) VALUES (%s, %s, '%s');",
                        universityId, departmentId, departmentName
                );

                // 생성된 SQL 문을 파일에 쓰고 줄바꿈
                writer.write(insertSql);
                writer.newLine();
                successCount++;
            }

            System.out.println("✅ " + successCount + "개의 학과 데이터에 대한 SQL 파일 생성이 완료되었습니다.");
            System.out.println("   -> 저장된 파일: " + outputFilePath);

        } catch (IOException e) {
            System.err.println("❌ 파일 처리 중 오류가 발생했습니다: " + e.getMessage());
            e.printStackTrace();
        }
    }
}